kind = "web"
previewPath = "/"
title = "Universe Moon [Um]"
version = "1.0.0"
id = "artifacts/universe-moon"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26156

[services.development]
run = "pnpm --filter @workspace/universe-moon run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/universe-moon", "run", "build" ]
publicDir = "artifacts/universe-moon/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26156"
BASE_PATH = "/"
